# Generated by Django 3.2.8 on 2021-10-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=1000)),
                ('details', models.CharField(blank=True, max_length=4000, null=True)),
                ('category', models.CharField(max_length=90)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('seller_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=90, unique=True)),
                ('phone', models.CharField(max_length=90, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('approval_status', models.CharField(max_length=90)),
                ('gst_number', models.CharField(max_length=90, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='sellerimages/')),
            ],
            options={
                'db_table': 'sellers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=90, unique=True)),
                ('phone', models.CharField(max_length=90, unique=True)),
                ('is_phone_verified', models.CharField(max_length=90)),
                ('is_email_verified', models.CharField(max_length=90)),
                ('cart_id', models.CharField(max_length=90, unique=True)),
                ('wishlist_id', models.CharField(max_length=90, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='userimages/')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.products')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.users')),
            ],
            options={
                'db_table': 'wishlist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('address_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('house_no', models.CharField(max_length=90)),
                ('address_line1', models.CharField(max_length=400)),
                ('address_line2', models.CharField(blank=True, max_length=400, null=True)),
                ('landmark', models.CharField(blank=True, max_length=400, null=True)),
                ('city_village_name', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('pincode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.users')),
            ],
            options={
                'db_table': 'user_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SellerAddresses',
            fields=[
                ('address_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('house_no', models.CharField(max_length=90)),
                ('address_line1', models.CharField(max_length=400)),
                ('address_line2', models.CharField(blank=True, max_length=400, null=True)),
                ('ciyt_village_name', models.CharField(max_length=90)),
                ('landmark', models.CharField(blank=True, max_length=400, null=True)),
                ('state', models.CharField(max_length=90)),
                ('pincode', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.sellers')),
            ],
            options={
                'db_table': 'seller_addresses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('return_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.users')),
            ],
            options={
                'db_table': 'returns',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.sellers'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productimages/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.products')),
            ],
            options={
                'db_table': 'product_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DelliverablePincodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('no_of_days_to_deliver', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.sellers')),
            ],
            options={
                'db_table': 'delliverable_pincodes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Checkouts',
            fields=[
                ('checkout_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('delivery_status', models.CharField(max_length=90)),
                ('shipping_address_id', models.CharField(max_length=90)),
                ('expected_date', models.DateTimeField()),
                ('ordered_date', models.DateTimeField()),
                ('kart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.users')),
            ],
            options={
                'db_table': 'checkouts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.users')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estore.products')),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
            },
        ),
    ]
