# Generated by Django 3.2.8 on 2021-11-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='active',
            field=models.CharField(choices=[('TRUE', 'true'), ('FALSE', 'flase')], default='TRUE', max_length=5),
        ),
        migrations.AddField(
            model_name='users',
            name='deleted',
            field=models.CharField(choices=[('TRUE', 'true'), ('FALSE', 'flase')], default='FALSE', max_length=5),
        ),
    ]
