# Generated by Django 3.2.8 on 2021-11-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_auto_20211101_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
