# Generated by Django 3.2.8 on 2021-11-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0003_alter_users_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=0),
        ),
    ]
