# Generated by Django 3.2.7 on 2021-11-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0003_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_m',
            field=models.BooleanField(default=False),
        ),
    ]
