# Generated by Django 3.2.7 on 2021-11-10 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_users_is_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='id',
        ),
        migrations.AddField(
            model_name='logs',
            name='log_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
