# Generated by Django 3.2.8 on 2021-11-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_alter_users_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
    ]
