# Generated by Django 3.2.8 on 2021-11-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0005_alter_users_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
