# Generated by Django 3.2.8 on 2021-11-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_alter_users_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_email_verified',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_phone_verified',
            field=models.BooleanField(default=0),
        ),
    ]
